### ISSUE TITLE
This is regarding class not found error of Captcha plugin .

### ISSUE THREAD

**Issue by dpkrai96** [ivanamat/cakephp3-captcha#1]
Hi  
     I am using cakephp 3.3.3 and everything gonna alright .I have put your plugins in plugins/Captcha dir
And also configure the config/bootstrap.php as 
`Plugin::load('Captcha');
Configure::write('Captcha.secret','mysecrete` key bla bla bla');`

after that I have load the component in my controller as
`<?php	 

	namespace App\Controller;

	 

	use App\Controller\AppController;
        use Cake\Network\Exception\NotFoundException;
        use Cake\View\Exception\MissingTemplateException;
	 
	class DealershipController extends AppController

	{
	 
	public function initialize()
	    {
	        parent::initialize();

	        $this->loadComponent('Flash'); // Include the FlashComponent
                $this->loadComponent('RequestHandler');
                $this->loadComponent('Captcha.Captcha');
 
                $this->loadModel('Dealerships');
                $this->loadModel('States');
                $this->loadModel('Cities');
                $this->loadModel('Cpomanufacturers');
                $this->loadModel('Providers');
                
	    }`

**Comment by ivanamat** [comment]
Try to install using composer and tell me if everything is installed properly. Thank you.

Regards,

**Comment by ShananCH** [comment]
Hello,
I have the same problem with cakephp 3.3.15.

Best regards

**Comment by ivanamat** [comment]
Hi all

Read this https://book.cakephp.org/3.0/en/plugins.html#autoloading-plugin-classes if you install plugin in plugins path.
